import { Roboto, Poppins } from "next/font/google";
import "./globals.css";
import { MenuLateral } from "@/components/menu/lateral/MenuLateral";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-poppins",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt" className="overflow-y-scroll">
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <body
        className={`${poppins.variable} ${roboto.variable} antialiased select-none`}
      >
        <div className="flex justify-center min-h-screen">
          {/* Container central */}
          <div
            id="container"
            className="flex w-full md:max-w-[768px] min-h-screen relative"
          >
            <main className="flex-1">{children}</main>
          </div>

          {/* Menu fixo na lateral do container */}
          <MenuLateral />
        </div>
      </body>
    </html>
  );
}
