import { Roboto, Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-poppins",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt">
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <body className={`${poppins.variable} ${roboto.variable} antialiased`}>
        <div className="flex justify-center min-h-screen bg-gray-200">
          <div className="flex w-full md:max-w-[800px] min-h-screen bg-gray-100 shadow-lg">
            <aside className="hidden md:flex w-24 bg-gray-200 text-black flex-col p-4">
              <nav className="flex w-full  flex-col gap-0.5">
                <a
                  href="#"
                  className=" bg-gray-100 h-[75px] flex items-center justify-center  text-sm"
                >
                  Caixa
                </a>
                <a
                  href="#"
                  className="bg-gray-100 h-[75px] flex items-center justify-center  text-sm"
                >
                  Comandas
                </a>
                <a
                  href="#"
                  className="bg-gray-100 border-gray-300 h-[75px] flex items-center justify-center  text-sm"
                >
                  Atendimento
                </a>
                <a
                  href="#"
                  className="bg-gray-100 border-gray-300 h-[75px] flex items-center justify-center  text-sm"
                >
                  Config
                </a>
              </nav>
            </aside>
            <main className="flex-1 p-4">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
