import { Roboto, Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-poppins",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 1,
    userScalable: "no",
  },
  manifest: "/manifest.json",
  themeColor: "#9333ea",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt" className="overflow-y-scroll">
      <body
        className={`${poppins.variable} ${roboto.variable} antialiased `} //select-none
      >
        <div className="flex justify-center min-h-screen">
          {/* Container central */}
          <div
            id="container"
            className="flex w-full md:max-w-[768px] min-h-screen relative"
          >
            <main className="flex-1  dark:shadow-fuchsia-500 shadow-2xl">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
