const MASTER = "MASTER";
const ADMIN = "ADMIN";
const MODERATOR = "MODERATOR";
const VIEWER = "VIEWER";

export const RULES = {
  MODERATOR: [MASTER, ADMIN, MODERATOR],
  ADMIN: [MASTER, ADMIN],
};

// Exemplo de uso
export const CORES_FIXAS = [
  "#007BFF",
  "#28A745",,
  "#FFC107",
  "#6F42C1",
  "#20C997",
  "#FD7E14",
  "#17A2B8",
  "#E83E8C",
  "#6C757D",
  "#3393FF",
  "#57B96E",
  "#E65E6B",
  "#FFD345",
  "#956AD2",
  "#4FDBB1",
  "#FF9D4D",
  "#4AADC7",
  "#ED68A7",
  "#8E959B",
  "#66AFFF",
  "#85CC98",
  "#F08691",
  "#FFE584",
  "#BC93E4",
  "#7EEFD0",
  "#FFBC85",
  "#7DE6D6",
  "#F292C2",
  "#AFAEB3",
  "#99C6FF",
  "#B4DEBD",
  "#F6AFB7",
  "#FFF2C2",
  "#E2BDEE",
  "#ACEFEA",
  "#FFDCE0",
  "#AFEBEC",
  "#F7BBDD",
  "#D0D1D4",
  "#CCE2FF",
  "#E3F2E8",
  "#FBE0E3",
  "#FFF9E1",
  "#F0E0F7",
  "#DAF8F4",
  "#FFE2E0",
  "#DAF5F7",
  "#FAE6F1",
  "#ECEDED",
];

const optionsColors = [
  { type: "btn-blue", name: "Azul" },
  { type: "btn-purple", name: "Roxo" },
  { type: "btn-green", name: "Verde" },
  { type: "btn-gray", name: "Cinza" },
  { type: "btn-orange", name: "Laranja" },
  { type: "btn-red", name: "Vermelho" },
];

export const BUTTON_THEMES = {
  'btn-purple': {
    "--button-default": "#9B59B6",
    "--button-hover": "#AF7AC5",     
    "--button-focus": "#8E44AD",     
    "--button-pressed": "#82589F",  
    "--button-disabled": "#D2B4DE", 
    "--button-progress": "#BB8FCE", 
  },
  'btn-green': {
    "--button-default": "#2ECC71",
    "--button-hover": "#58D683",
    "--button-focus": "#27AE60",
    "--button-pressed": "#28B463",
    "--button-disabled": "#A9DFBF",
    "--button-progress": "#52BE80",
  },
  'btn-gray': {
    "--button-default": "#95A5A6",
    "--button-hover": "#AABEB2",
    "--button-focus": "#7F8C8D",
    "--button-pressed": "#88999A",
    "--button-disabled": "#D5DBDB",
    "--button-progress": "#BFC9CA",
  },
  'btn-blue': {
    "--button-default": "#3498DB",
    "--button-hover": "#5DADE2",
    "--button-focus": "#2E86C1",
    "--button-pressed": "#2874A6",
    "--button-disabled": "#A9CCE3",
    "--button-progress": "#5DADE2",
  },
'btn-pink': {
  "--button-default": "#E83E8C", 
  "--button-hover": "#F06292",   
  "--button-focus": "#C2185B",
  "--button-pressed": "#D81B60", 
  "--button-disabled": "#FCE4EC",
  "--button-progress": "#EC407A",
},
  'btn-orange': {
    "--button-default": "#FF9900",
    "--button-hover": "#FFB84D",
    "--button-focus": "#CC7A00",
    "--button-pressed": "#D98500",
    "--button-disabled": "#FFDDAA",
    "--button-progress": "#FFC066",
  },
};